app/api/urls.py
from django.urls import path

from .views import PhotoLoader, SecondPhotoLoader


app_name = 'api'


urlpatterns = [
    path('load_photo/', PhotoLoader.as_view(), name='api_photo_loader'),
    path('add_photo/', SecondPhotoLoader.as_view(), name='api_photo_loader'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photos.urls', namespace='photos')),
    path('api/', include('api.urls', namespace='api')),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/redoc/',
         SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

app/photos/urls.py
from django.urls import path

from .views import index


app_name = 'photos'


urlpatterns = [
    path('', index, name='index')
]

app/photos/models.py
from random import randint

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Photo(models.Model):

    image_name = models.CharField(
        "Наименование файла",
        max_length=50,
    )
    file = models.ImageField(
        "Файл",
        upload_to="images/",
    )
    random_int = models.IntegerField(
        "Рандомное значение",
        validators=[MinValueValidator(1), MaxValueValidator(1000)],
        default=randint(1, 1000),
    )
    load_time = models.DateTimeField(
        "Время сохранения",
        auto_now_add=True,
    )

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"
        ordering = ("-id",)

    def __str__(self):
        return self.image_name

app/api/views.py
from random import randint
from time import sleep

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from drf_spectacular.utils import extend_schema

from photos.consumers import update_photo

from .tasks import add
from .serializers import PhotoSerializer, PhotoResponseSerializer


class PhotoLoader(APIView):
    """
    Принимает POST запрос с изображением в кодировке base64
    и сохраняет его в БД, возвращает сгенерированное случайное число
    в диапазоне от 1 до 1000.
    """

    @extend_schema(
        request=PhotoSerializer,
        responses=PhotoResponseSerializer,
        operation_id='Загрузка фото',
    )
    def post(self, request):
        serializer = PhotoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            # Я тут не совсем понял насчет 20 секунд...
            # Нужно дать ответ через 20 секунд? Тогда можно имитацию
            # c sleep. Конечно, для реального проекта не сгодится, там
            # от контекста нужно исходить.
            sleep(20)
            update_photo()
            # Если имелось ввиду отдать ответ сразу, а саму картинку
            # обрабатывать 20 секунд, то ниже я написал класс, который
            # сохранит картинку асинхронно через 20 секунд, а ответ
            # отдаст сразу
            return Response(
                serializer.instance.random_int, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class SecondPhotoLoader(APIView):
    """
    Принимает POST запрос с изображением в кодировке base64
    и сохраняет его в БД, возвращает сгенерированное случайное число
    в диапазоне от 1 до 1000.

    В данном случае, ответ возвращается сразу, а картинка сохранится
    только через 20 секунд. Появится сама на главной странице тоже
    только через 20 секунд.
    """

    @extend_schema(
        request=PhotoSerializer,
        responses=PhotoResponseSerializer,
        operation_id='Загрузка фото',
    )
    def post(self, request):
        number = randint(1, 1000)
        serializer = PhotoSerializer(data=request.data)
        if serializer.is_valid():
            add.apply_async(args=[serializer.data, number], countdown=20)
            return Response(
                number, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

app/photos/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import Photo
from .tasks import test_add


def index(request):
    """
    Рендерит главную страницу.
    """
    template = 'index.html'
    photos = Photo.objects.all()
    paginator = Paginator(photos, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    if request.method == "POST":
        file = request.FILES.get('file')
        if file:
            photo = Photo.objects.create(
                image_name=file.name,
                file=file,
            )
            test_add.apply_async(args=[photo.id], countdown=20)
    return render(request, template, context)

app/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
    <title>Photo Loader</title>
</head>
<body>
    <main>
        <div class="container p-3 mt-4 mb-4">
            <form class="test-form" method="post" action="{% url 'photos:index' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="input-file">
                    <div>
                        <input type="file" name="file" accept=".jpg, .jpeg, .png">		
                        <span>Выберите файл</span>
                    </div>
                    <div>
                        <button type="input" class="btn btn-dark mt-3">Загрузить</button>
                    </div>
                </label>
            </form>
            <div id="display">
            {% if page_obj %}
                <div class="table-responsive mt-4">
                    <table class="table table-striped text-center">
                        <thead>
                            <tr>
                                <th scope="col">Число</th>
                                <th scope="col">Наименование</th>
                                <th scope="col">Дата и время загрузки</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for photo in page_obj %}
                                <tr>
                                    <th scope="row">{{ photo.random_int }}</th>
                                    <td>{{ photo.image_name }}</td>
                                    <td>{{ photo.load_time }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="paginator_block">
                    {% if page_obj.has_other_pages %}
                    <nav aria-label="Page navigation" class="my-5">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <
                                </a>
                            </li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <span class="page-link">{{ i }}</span>
                                </li>
                                {% elif num > files.number|add:'-3' and num < files.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}p</a>
                                </li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                >
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                                    {{ page_obj.paginator.num_pages }}
                                </a>
                            </li>
                            {% endif %}    
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            {% endif %}
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script
        src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
        crossorigin="anonymous">
    </script>
    <script>
    $('.input-file input[type=file]').on('change', function(){
        let file = this.files[0];
        $(this).next().html(file.name);
    });
    </script>
    <script>
        var wsStart = 'ws://';
        if (window.location.protocol == 'https:') {
            wsStart = 'wss://'
        };
        const socket = new WebSocket(wsStart + `${window.location.host}/ws/photos/`);

        // Обработчик открытия соединения
        socket.addEventListener('open', (event) => {
            console.log('WebSocket connection opened:', event);
        });

        // Обработчик получения сообщения
        socket.addEventListener('message', (event) => {
            const data = JSON.parse(event.data);
            console.log(data.message);
            $("#display").load(location.href + " #display");
        });

        // Обработчик закрытия соединения
        socket.addEventListener('close', (event) => {
            console.log('WebSocket connection closed:', event);
        });

    </script>
</body>
</html>